src/main/java/net/wurstclient/serverfinder/CleanUpScreen.java
Fixed a crash issue where server.label is null, so calling equals() will crash.
**NOTE:** If you are contributing multiple unrelated features, please create a separate pull request for each feature. Squeezing everything into one giant pull request makes it very difficult for us to add your features, as we have to test, validate and add them one by one.
Thank you for your understanding - and thanks again for taking the time to contribute!!
=> Fixed crash on cleanup

src/main/java/net/wurstclient/hacks/AntiKnockbackHack.java
These settings help closet cheating. Vertical antikb is easily detectable, but horizontal antikb is harder to detect.
=> Add Vertical Strength and Horizontal Strength settings to AntiKnockback hack

src/main/java/net/wurstclient/mixin/ScreenMixin.java, src/main/resources/wurst.mixins.json
Right now, a server is able to force a player into running a Wurst command through a chat message with a "ClickEvent" tag. This is already used to prevent the client from joining (#94), but a malicious server can easily mess with the client through chat messages. With this fix, all commands sent by clicking the chat message will bypass the Wurst command system.
=> [Critical] Prevent Servers from Running Wurst Commands

src/main/java/net/wurstclient/altmanager/screens/AltEditorScreen.java
My minecraft account has a very long password and I was unable to add it to your client, I had already fixed this in another fork but I figured I'd make a PR for you.
The password field now supports passwords up to 64 chars in length.
=> Fixed issue with long passwords in altmgr

src/main/java/net/wurstclient/hacks/ChestEspHack.java, src/main/java/net/wurstclient/mixin/WorldMixin.java, src/main/java/net/wurstclient/mixinterface/IWorld.java
Fixed ChestESP using `blockEntityTickers` in world needed to use a Mixin to get the protected field.
=> Fixed ChestESP on 20w45a fixes #206

src/main/java/net/wurstclient/hacks/SearchHack.java
Currently, Search does not check if the chunk at the location exists, leading to "empty" chunks being added. This PR fixes the issue by adding a check when chunks in range are loaded in.
=> Fix SearchHack empty chunks

src/main/java/net/wurstclient/hacks/FeedAuraHack.java
What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)
The default FeedAura automatically feeds any mobs that can be fed with the item held in hand. This includes babies. Feeding babies will cause them to grow faster, but at the expense of more food. Adding an option to filter out babies means that a user can choose to save food by not feeding babies and letting them grow by themselves.
If applicable, add screenshots or videos to help explain your pull request.
=> FeedAura baby filter

src/main/java/net/wurstclient/hacks/FullbrightHack.java, src/main/java/net/wurstclient/mixin/GameRendererMixin.java, src/main/java/net/wurstclient/mixin/LivingEntityMixin.java, src/main/resources/wurst.mixins.json
Gives the night vision effect without the potion effect showing up.
This is helpful because if the player already has the night vision potion effect, toggling this mod wouldn't remove it.
=> Better Night Vision

src/main/java/net/wurstclient/hacks/TreeBotHack.java
Fixing game crash when deactivating Tree Bot caused by tree being null
[STDERR]: java.lang.NullPointerException: Cannot invoke "net.wurstclient.treebot.Tree.close()" because "this.tree" is null
[STDERR]: 	at net.wurstclient.hacks.TreeBotHack.onDisable(TreeBotHack.java:116)
=> Added null ckeck Before Calling tree.close();

src/main/resources/assets/wurst/lang/zh_tw.json
update zh_tw
Should i change following (I'll keep the original words for now): （我是否要修改以下幾點，當前暫時保留原詞）
"AltManager" to "賬號管理器"(Account Manager)
"Alt" to “賬號”(Account)
"Alt List" to "賬號列表"(Account list)
Because the function of it is manage account and "ALT" it self is the account or cracked account（因爲ALT這個詞本身就是賬戶相關的，如果保留會對高級用戶和其他語言用戶的交流更加友好，如果修改爲“賬號”類的，新手更加易懂）
=> Update new translation of zh_tw

src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java
Fix injection of Wurst options button so it doesn't interfere with such mods as ModMenu (fixes https://github.com/Wurst-Imperium/Wurst7/issues/546).
Now it looks for `menu.options` button (vanilla options), inserts Wurst options here and shifts all next buttons down.
Also uses `Screens.getButtons` instead of direct `addDrawableChild` call so game screen maintains correct order of child widgets and other mods can also inject their buttons without interfering with Wurst button (given they do it properly). 
Result:
**ModMenu installed**
**Without ModMenu**
=> Fix injection of Wurst options button

src/main/java/net/wurstclient/hacks/NoFireOverlayHack.java, src/main/java/net/wurstclient/mixin/InGameOverlayRendererMixin.java
This PR adds an option to lower the fire overlay. Currently, the only options are to eliminate the fire overlay or to have the overlay block half the screen, both of which have their downsides.
This is an updated version of #118.
=> Option to lower fire overlay

src/main/java/net/wurstclient/hacks/NoBackgroundHack.java, src/main/java/net/wurstclient/mixin/ScreenMixin.java
This PR disables NoBackground when a world is not loaded, as well as an option to only remove the background from inventories.
This fix combines #621 and #335 to allow users to choose if they want the non-inventory GUIs to have the background.
=> More options for nobackground

src/main/java/net/wurstclient/events/VelocityFromFluidListener.java, src/main/java/net/wurstclient/hacks/AntiWaterPushHack.java, src/main/java/net/wurstclient/mixin/EntityMixin.java
Closes #767. Now NoWaterPush will no longer affect entities that are not the player.
=> Fix AntiWaterPush affecting other entities

src/main/java/net/wurstclient/hacks/NameTagsHack.java, src/main/java/net/wurstclient/mixin/EntityRendererMixin.java, src/main/java/net/wurstclient/mixin/LivingEntityRendererMixin.java
Closes #739.
-Removes the distance limitation of nametags (normally set to 4,096 blocks distance squared)
-Add option to force show nametags (for example the player model in the inventory screen) (it is possible for servers to hide player nametags, this option ignores this constraint)
-Make nametags show clearly through walls. You can see the differences below:
Before:
After:
=> NameTags Improvements

src/main/java/net/wurstclient/mixin/ChatHudMixin.java
Closes #761. In the mixin, logChatMessage is skipped, resulting in chat messages not being logged.
Credit to isjerryxiao for suggesting this fix.
=> Fix chat messages not being logged

src/main/java/net/wurstclient/hacks/FeedAuraHack.java
Adds some more options for FeedAura.
- Filter untamed animals, as feeding them is not necessary for taming.
- Filter horses, llamas, and donkeys. This is because of a [bug](https://bugs.mojang.com/browse/MC-233276) that causes these entities to consume items infinitely. You can check this by being in survival mode with a stack of golden carrots while being next  to a horse with FeedAura enabled.
=> More FeedAura options

src/main/java/net/wurstclient/events/ShouldDrawSideListener.java, src/main/java/net/wurstclient/events/TesselateBlockListener.java, src/main/java/net/wurstclient/hacks/XRayHack.java, src/main/java/net/wurstclient/mixin/BlockMixin.java, src/main/java/net/wurstclient/mixin/BlockModelRendererMixin.java, src/main/java/net/wurstclient/mixin/FluidRendererMixin.java, src/main/java/net/wurstclient/mixin/SodiumBlockOcclusionCacheMixin.java, src/main/java/net/wurstclient/mixin/TerrainRenderContextMixin.java, src/main/java/net/wurstclient/settings/BlockListSetting.java
This is a feature for X-Ray to deal with servers utilizing Anti-X-Ray. This is not a bypass, but rather a band-aid that makes X-Ray not outright useless on these servers (https://github.com/Wurst-Imperium/Wurst7/issues/860). 
When X-Ray is enabled and the feature 'Show exposed' is toggled to enable, sometimes nothing changes. Disabling and enabling X-Ray seems to show the changes.
`BlockUtils.canBeClicked` is what is currently being used. Should fences, leaves, and other non-solid blocks be considered? Currently only air, water and lava are the primary exposed blocks. I left some comments and unused code that shows what I mean in reference to some non-solid blocks when initially testing.
X-Ray disabled
X-Ray enabled
=> Anti-X-Ray exposed blocks

src/main/java/net/wurstclient/settings/filters/FilterSleepingSetting.java
Sleeping filter not correctly targeting players in sleep pose while not sleeping in bed.
This can be tested in a Hypixel Murder Mystery game. Prior to this change, fallen players would still be shown although sleeping filter is enabled.
=> Fixed sleeping filter

src/main/java/net/wurstclient/keybinds/KeybindProcessor.java
This change fixes an issue where trying to use a debug key combo (e.g. F3+B to show hitboxes, or F3+G to show chunk boundaries) would also trigger any keybinds tied to those keys (in the previous example, it would trigger FastBreak/Place or Flight respectively with default keybinds)
=> 🪲 Don't trigger keybinds if we're trying to use an F3 debug command

src/main/java/net/wurstclient/hacks/AimAssistHack.java
Added a new feature to the codebase: `onlyAllowWhileClicking` CheckboxSetting. When enabled, this setting prevents the aim from targeting entities when the attack key is not pressed.
I have tested these changes by enabling the `onlyAllowWhileClicking` setting and verifying that the aim does not target entities when the attack key is not pressed. Additionally, I have checked that the aim behaves as expected when the setting is disabled. I recommend the reviewer to perform similar tests to validate the functionality.
No related issues or forum posts at the moment.
=> Add new setting to AimAssist `onlyAllowWhileClicking`

src/main/java/net/wurstclient/hacks/AirPlaceHack.java, src/main/resources/assets/wurst/lang/en_us.json
> What have you added and what does it do? (Alternatively, what have you fixed and how does it work?)
Added optional guide boxes for airplace hack to show where the block will be placed (off by default)
Sort of fix/feature for https://github.com/Wurst-Imperium/Wurst7/issues/1014 but more just qol
> How have you tested your changes? Any testing tips for the reviewer?
Tested multiplayer and singleplayer, with different colors, ranges, and other render-related hacks
> List any related issues, forum posts, videos and such here.
https://youtu.be/chV8J5KHzuQ
=> Added option for guide boxes to show where airplace will place blocks

src/main/java/net/wurstclient/mixin/ClientCommonNetworkHandlerMixin.java
PacketOutputEvent includes a way to replace the packet being sent through setPacket(), but it never actually worked.
The only mod that uses the setPacket() feature is AntiHunger.
=> Fix PacketOutputEvent

src/main/java/net/wurstclient/hacks/TriggerBotHack.java
Fixed NPE produced in `TriggerBotHack` when leaving a server.
Most likely introduced in a recent commit that changed `HandleInputEvent` injection point (0d50ef6)
https://github.com/user-attachments/assets/c3a15b11-520e-45bc-aad2-d355470d9f47
=> Fix TriggerBotHack NPE

src/main/java/net/wurstclient/altmanager/MicrosoftLoginManager.java, src/main/java/net/wurstclient/mixin/MinecraftClientMixin.java
Fixes #1068.
This PR only creates the ProfileKeys if the user is logged in to a Microsoft account. This is the way it is done in the vanilla code.
=> ProfileKeys fix

src/main/java/net/wurstclient/serverfinder/ServerFinderScreen.java
Fixed the loop in `updatePingers()` not decrementing a counter when a pinger instance is removed. (Why not just use removeIf though?)
Patch was tested separately from the project, works fine.
=> fix skipping over pingers

src/main/java/net/wurstclient/util/FakePlayerEntity.java
FakePlayerEntity now always spawns correctly.
Resolves #1096 
https://github.com/user-attachments/assets/afbaaa81-2abc-401c-ab44-56e28cc49123
=> Fix FakePlayerEntity

src/main/java/net/wurstclient/clickgui/components/RadarComponent.java, src/main/java/net/wurstclient/settings/filters/FilterPassiveSetting.java, src/main/java/net/wurstclient/settings/filters/FilterPassiveWaterSetting.java
Needed because the respective mob classes don't extend WaterCreatureEntity in the latest versions (1.21.1 is not affected).
=> Add squids/dolphins back to passive mob filters

src/main/java/net/wurstclient/mixin/ChatHudMixin.java
Previously, the modified message from `ChatInputEvent` would not be reassigned correctly in `ChatHudMixin` after it was modified.
Only `AntiSpamHack` was affected by this issue.
=> Fix ChatInputEvent message assignment

src/main/java/net/wurstclient/commands/ModifyCmd.java, src/main/java/net/wurstclient/commands/ViewCompCmd.java
`ModifyCmd` and `ViewCompCmd` did not work for some component types because Ops should be accessed via registry manager.
`ModifyCmd` also lacked a null check in `set`.
Before fix:
```
Result: DataResult.Error['Can't access registry ResourceKey[minecraft:root / minecraft:enchantment] missed input: {"efficiency":3}': ItemEnchantments{enchantments={}}]
Value: ItemEnchantments{enchantments={}}
```
After fix:
```
Result: DataResult.Success[ItemEnchantments{enchantments={Reference{ResourceKey[minecraft:enchantment / minecraft:efficiency]=Enchantment Efficiency}=>3}}]
Value: ItemEnchantments{enchantments={Reference{ResourceKey[minecraft:enchantment / minecraft:efficiency]=Enchantment Efficiency}=>3}}
```
Before:
```
enchantments => null
damage => 2
tool => null
enchantable => {"value":10} …
```
=> Fix component commands

src/main/java/net/wurstclient/hacks/GlideHack.java
See #368, no more formatting issues and stuff.
=> Add option to temporarily disable Glide hack while sneaking

src/main/java/net/wurstclient/mixin/BackgroundRendererMixin.java
Fixed NoFog
> At some point in updating the version of the client, the code for NoFog was changed. Instead of just removing the terrain fog, all fog was removed. This made the sky have a sharp line where it should be blended with fog. I added this back to make the sky look normal.
> I've tested this in game to make sure the sky is correct.
=> Fixed NoFog

src/main/java/net/wurstclient/util/FakePlayerEntity.java
When using Blink hack, player would get pushed away on collision with the fake player.
Before:
https://github.com/user-attachments/assets/7d30dbe4-2261-4eef-ac52-d2d96732124d
After:
https://github.com/user-attachments/assets/f9cc592b-62ff-4ef5-9c51-b7b7200ee02c
=> Fix FakePlayerEntity pushing away the player

src/main/java/net/wurstclient/clickgui/components/RadarComponent.java
Fixed the rotation of the player arrow (visible when `Rotate with player` is disabled).
It now works the same way it did prior to 1.21.6 update.
=> Fix Radar player arrow rotation
