src/main/java/net/wurstclient/commands/EnchantCmd

**NOTE:** If you are contributing multiple unrelated features, please create a separate pull request for each feature. Squeezing everything into one giant pull request makes it very difficult for us to add your features, as we have to test, validate and add them one by one.
Thank you for your understanding - and thanks again for taking the time to contribute!!

Add EnchantCmd

---

src/main/java/net/wurstclient/hacks/AutoStealHack.java
src/main/java/net/wurstclient/mixin/ShulkerBoxScreenMixin.java
src/main/resources/wurst.mixins.json

Added Shulker Box support to AutoSteal hack.

Added Shulker Box support to AutoSteal

---

src/main/java/net/wurstclient/hacks/MobSpawnEspHack.java

This option reveals out-of-sight areas where mobs can spawn.
Note: It's a bit annoying to have enabled all the time, but it's invaluable when trying to hunt down unlit areas. (Once `SetCheckboxCmd` is eventually implemented, using that to set up a hotkey to turn this MobSpawnESP option on and off will improve the user experience significantly.)

Add X-Ray option to MobSpawnESP

---

src/main/java/net/wurstclient/hacks/AutoFarmHack.java

Fixes #283
I templated it off 591ec9d6b79a74e5301931c9e7ebbcbc35145e7b, but I do not have a development environment, so I have not been able to test it.

Add cocoa support to AutoFarmHack

---

src/main/java/net/wurstclient/hack/HackList.java
src/main/java/net/wurstclient/hacks/NoGuiBackgroundHack.java
src/main/java/net/wurstclient/mixin/ScreenMixin.java
src/main/resources/wurst.mixins.json

This removes the black background in GUI. It makes it easier to notice an approach of an enemy.
NoGuiBackground disabled:
NoGuiBackground enabled:

Add NoGuiBackground hack

---

src/main/java/net/wurstclient/hacks/FlightHack.java
src/main/java/net/wurstclient/hacks/FreecamHack.java

I have corrected all velocity spelling mistakes

Velocity typos

---

src/main/java/net/wurstclient/clickgui/screens/EditBlockListScreen.java
src/main/java/net/wurstclient/clickgui/screens/EditBlockScreen.java
src/main/java/net/wurstclient/clickgui/screens/EditItemListScreen.java

Fixes #413
Current max length is 32 characters, meanwhile longest id is 41
Increases character length to 64 in all of the screens that require it.

Character limit increase

---

src/main/resources/assets/wurst/lang/zh_tw.json

Added some traditional Chinese translations of Wurst

Added some traditional Chinese translations of Wurst

---

src/main/resources/assets/wurst/lang/zh_cn.json

Translate new content of AltManager. English to Chinese.

Translation of new content

---

src/main/java/net/wurstclient/hack/HackList.java
src/main/java/net/wurstclient/hacks/NocomCrashHack.java
src/main/resources/assets/wurst/lang/en_us.json

Uses the nocom exploit to cause servers to load lots of chunks at once and lag a lot, or even crash
[Not my video but this is it](https://www.youtube.com/watch?v=f0pT6rJnrCA)

Add nocom crash

---

src/main/resources/assets/wurst/lang/zh_cn.json
src/main/resources/assets/wurst/lang/zh_tw.json

Added and optimize translation of "nocomcrash"

Update "zh_cn","zh_tw" translation to the latest version

---

src/main/resources/assets/wurst/lang/pl_pl.json

Add "nocomcrash" to pl_pl translation

---

src/main/java/net/wurstclient/altmanager/Alt.java
src/main/java/net/wurstclient/altmanager/AltManager.java
src/main/java/net/wurstclient/altmanager/AuthenticationException.java
src/main/java/net/wurstclient/altmanager/LoginManager.java
src/main/java/net/wurstclient/altmanager/MicrosoftLoginManager.java
src/main/java/net/wurstclient/altmanager/MinecraftProfile.java
src/main/java/net/wurstclient/altmanager/MojangAlt.java
src/main/java/net/wurstclient/altmanager/XBLToken.java
src/main/java/net/wurstclient/altmanager/screens/AltManagerScreen.java
src/main/java/net/wurstclient/altmanager/screens/DirectLoginScreen.java

Added Microsoft authentication. If no Microsoft account is found, it will attempt a Mojang login. However, I don't have a Mojang account to test, although it should work.

Add Microsoft authentication.

---

src/main/java/net/wurstclient/hacks/KillauraHack.java
src/main/java/net/wurstclient/hacks/KillauraLegitHack.java

Adds damageIndicator to Killaura and KillauraLegit
Fixes #615

Add damageIndicator option

---

src/main/java/net/wurstclient/hack/HackList.java
src/main/java/net/wurstclient/hacks/NoLevitationHack.java
src/main/java/net/wurstclient/mixin/LivingEntityMixin.java
src/main/resources/wurst.mixins.json

NoLevitation disables the levitation status effect (typically given by the Shulker mob)
Video demo: https://youtu.be/eiY9BhyQWn0

Created the original NoLevitation hack

---

src/main/java/net/wurstclient/hacks/AutoReconnectHack.java
src/main/java/net/wurstclient/mixin/DisconnectedScreenMixin.java

Adds a "Wait time" setting to AutoReconnect.
Issue #716

Add waitTime setting to AutoReconnectHack (issue #716)

---

src/main/java/net/wurstclient/hacks/AutoTotemHack.java

Adds a "Delay" setting to AutoTotem.
Issue #656

Add delay setting to AutoTotemHack (issue #656)

---

src/main/java/net/wurstclient/hack/HackList.java
src/main/java/net/wurstclient/hacks/CameraDistanceHack.java
src/main/java/net/wurstclient/mixin/CameraMixin.java
src/main/resources/assets/wurst/lang/en_us.json

This PR adds a hack called "CameraDistance" which lets you change the camera distance in 3rd person.

Add CameraDistance

---

src/main/java/net/wurstclient/hacks/ArrowDmgHack.java

Increase the maximum damage setting in ArrowDMG from 2000 to 7000 as per #702

Increase max ArrowDMG

---

src/main/java/net/wurstclient/hacks/TrajectoriesHack.java

This PR greatly improves the Trajectories hack by allowing to change the line's color when the arrow is going to hit an entity.

Change Trajectories color when hitting an entity

---

src/main/java/net/wurstclient/mixin/SodiumBlockOcclusionCacheMixin.java

Updated mixin target.
Resolves #863

Fix X-Ray not working with Sodium

---

src/main/java/net/wurstclient/hacks/AutoSprintHack.java
src/main/java/net/wurstclient/mixin/ClientPlayerEntityMixin.java

Adds an option to sprint in all directions. I've added a mixin at ClientPlayerEntity to prevent the sprint from being turned off if the player isn't moving forward.

Omnidirectional Sprint

---

src/main/java/net/wurstclient/mixin/LivingEntityRendererMixin.java

Changed the last appearance of redirect to WrapOperation. This is from the NameTags mod PR #770.

Convert Redirect to WrapOperation
